### ISSUE TITLE
Change to environment.yml

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/symbiflow-examples#19]
### Current

```bash
INSTALL_DIR="/opt/symbiflow/xc7"
bash conda_installer.sh -b -p $INSTALL_DIR/conda && rm conda_installer.sh
source "$INSTALL_DIR/conda/etc/profile.d/conda.sh"
conda update -y -q conda

wget -qO- https://storage.googleapis.com/symbiflow-arch-defs/artifacts/prod/foss-fpga-tools/symbiflow-arch-defs/continuous/install/4/20200416-002215/symbiflow-arch-defs-install-a321d9d9.tar.xz | tar -xJ -C $INSTALL_DIR
conda install -y -c symbiflow yosys yosys-plugins vtr-no-gui
conda install -y make lxml simplejson intervaltree git pip
conda activate
pip install python-constraint
pip install git+https://github.com/symbiflow/fasm
conda deactivate
```

### New version

```bash
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O conda_installer.sh
bash conda_installer.sh -b -p $INSTALL_DIR/conda

source "$INSTALL_DIR/conda/etc/profile.d/conda.sh"
conda env update --name xc7 --file xc7.yml
conda activate xc7
```

##### `environment.yml`
```yaml
name: xc7
channels:
- SymbiFlow
- defaults
dependencies:
- symbiflow
- yosys
- yosys-plugins
- vtr-no-gui
# Packages installed from PyPI
- pip:
  - -r file:requirements.txt
```

##### `requirements.txt`
```requirements.txt
python-constraint
-e git+https://github.com/symbiflow/fasm
```
